/*
 * FILE          : P01_ConfigTableCreation&InitialValues
 * PROJECT       : P01 - Configuration Table Creation
 * PROGRAMMER    : Julia Jakob
 * DESCRIPTION   : This script creates the Configuration Table with all of it's properties
 */

--DROP DATABASE Jubi; -- drop database if it already exists 

-- -- == CREATE THE DATABASE == --
-- CREATE DATABASE Jubi; -- temporary name for our project database
-- GO

-- -- == USE THE DATABASE == --
-- USE Jubi;
-- GO

USE master;
GO

IF DB_ID('Jubi') IS NOT NULL
BEGIN
    ALTER DATABASE Jubi SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Jubi;
END
GO

CREATE DATABASE Jubi;
GO

USE Jubi;
GO
 -------------------------------------------
 -- == CREATE TABLE == ---------------------
 -------------------------------------------
 CREATE TABLE Configuration (
	ConfigID INT IDENTITY (1,1) PRIMARY KEY, -- ID is auto-generated by system
	ConfigName VARCHAR(100) NOT NULL UNIQUE, -- Name of configuration
	ConfigValue VARCHAR(50) NOT NULL,		 -- Value of configuration
	DataType VARCHAR(20) NULL DEFAULT 'string', -- Data type of value for configuration (optional)
	Description VARCHAR(255) NULL            -- Description of what the configuration does (optional)
 );


 -------------------------------------------------
 -- == INSERT INITIAL VALUES == ------------------
 -------------------------------------------------
 INSERT INTO Configuration (ConfigName, ConfigValue, DataType, Description) VALUES
 -- Insert Bin Capacities ------------------------
 ('Harness.Capacity', '55', 'int', 'Bin capacity for harnesses'),
 ('Reflector.Capacity', '35', 'int', 'Bin capacity for reflectors'),
 ('Housing.Capacity', '24', 'int', 'Bin capacity for housings'),
 ('Lens.Capacity', '40', 'int', 'Bin capacity for lenses'),
 ('Bulb.Capacity', '60', 'int', 'Bin capacity for bulbs'),
 ('Bezel.Capacity', '75', 'int', 'Bin capacity for bezels'),

 -- Factory / Simulation Configurations -------------------------------
 ('LowStockThreshold', '5', 'int', 'Number of parts threshold to flag as low quantity'),
 ('TotalOrderQuantity', '500', 'int', 'Total number of lamps to build'),
 ('NumberOfWorkStations', '3', 'int', 'Number of work stations in the assembly area'),
 ('SimulationTimeScale', '1.0', 'decimal', 'Time scale for simulation'),

 -- Worker Time Configuration Values ----------------------------------------------
 ('BaseTime', '60.0','decimal','Base time for how fast it takes to assemble a completed fog lamp in seconds'),
 ('ExperiencedWorker.TimeVariationPercentage', '10.0','decimal','An experienced worker can assemble a completed fog lamp in the base time +/- this percentage'),
 ('NewEmployee.TimeVariationPercentage', '50.0','decimal','A new worker takes this percentage longer than the base time to complete a fog lamp'),
 ('SuperWorker.TimeVariationPercentage', '15.0','decimal','A super worker can complete a fog lamp in this percentage less time than the base time'),

 -- Worker Defect Rates -----------------------------------------------------------
 ('ExperiencedWorker.DefectRate', '0.5','decimal','A normal/experienced worker has this defect percentage'),
 ('NewEmployee.DefectRate', '0.85','decimal','A new worker has this defect percentage'),
 ('SuperWorker.DefectRate', '0.15','decimal','A super/ very experiencedworker has this defect percentage');

--------------------------------------------------------------------------------------
  --------------------------- == MILESTONE 2 == -----------------------------------
--------------------------------------------------------------------------------------


-- =========================================================
-- ASSEMBLY AREA
-- =========================================================
CREATE TABLE AssemblyArea
(
    AssemblyAreaID INT IDENTITY(1,1) PRIMARY KEY,
    TotalOrderQty INT NOT NULL DEFAULT 0,
    InProcessCount INT NOT NULL DEFAULT 0,
    ProducedCount INT NOT NULL DEFAULT 0,
    GoodLamps INT NOT NULL DEFAULT 0
);

-- =========================================================
-- WORK STATION
-- =========================================================
CREATE TABLE WorkStation
(
    StationID INT IDENTITY(1,1) PRIMARY KEY,
    StationName VARCHAR(100) NOT NULL UNIQUE,
    Status VARCHAR(30) NOT NULL,
    AssemblyAreaID INT NULL,
    Location VARCHAR(100) NULL,

    CONSTRAINT FK_WorkStation_AssemblyArea
        FOREIGN KEY (AssemblyAreaID) REFERENCES AssemblyArea(AssemblyAreaID)
);

-- =========================================================
-- SKILLS
-- =========================================================
CREATE TABLE Skills
(
    SkillLevelID INT IDENTITY(1,1) PRIMARY KEY,
    SkillLevelName VARCHAR(50) NOT NULL UNIQUE,
    Speed DECIMAL(6,2) NOT NULL,
    DefectRate DECIMAL(6,3) NOT NULL
);

-- =========================================================
-- WORKER
-- =========================================================
CREATE TABLE Worker
(
    WorkerID INT IDENTITY(1,1) PRIMARY KEY,
    WorkerName VARCHAR(100) NOT NULL,
    SkillLevelID INT NOT NULL,
    StationID INT NOT NULL,

    CONSTRAINT FK_Worker_Skills
        FOREIGN KEY (SkillLevelID) REFERENCES Skills(SkillLevelID),

    CONSTRAINT FK_Worker_WorkStation
        FOREIGN KEY (StationID) REFERENCES WorkStation(StationID)
);

-- =========================================================
-- PARTS
-- =========================================================
CREATE TABLE Parts
(
    PartID INT IDENTITY(1,1) PRIMARY KEY,
    PartName VARCHAR(50) NOT NULL UNIQUE,
    DefaultCapacity INT NOT NULL
);


-- =========================================================
-- BIN
-- =========================================================
CREATE TABLE Bin
(
    BinID INT IDENTITY(1,1) PRIMARY KEY,
    PartID INT NOT NULL,
    StationID INT NOT NULL,
    CurrentCount INT NOT NULL,
    NeedsRefill BIT NOT NULL DEFAULT 0,
    LastReplenishment DATETIME NULL,

    CONSTRAINT FK_Bin_Parts
        FOREIGN KEY (PartID) REFERENCES Parts(PartID),

    CONSTRAINT FK_Bin_WorkStation
        FOREIGN KEY (StationID) REFERENCES WorkStation(StationID),

    CONSTRAINT UQ_Bin_Station_Part
        UNIQUE (StationID, PartID)
);

-- =========================================================
-- TRAY
-- =========================================================
CREATE TABLE Tray
(
    TrayID INT IDENTITY(1,1) PRIMARY KEY,
    CreatedTime DATETIME NOT NULL DEFAULT GETDATE(),
    Capacity INT NOT NULL,
    TrayStatus VARCHAR(30) NOT NULL,
    SentToTestingTime DATETIME NULL
);

-- =========================================================
-- LAMPS
-- =========================================================
CREATE TABLE Lamps
(
    LampID INT IDENTITY(1,1) PRIMARY KEY,
    StationID INT NOT NULL,
    WorkerID INT NOT NULL,
    TrayID INT NULL,
    IsDefective BIT NOT NULL DEFAULT 0,
    AssemblyTime DECIMAL(8,2) NOT NULL,
    Barcode VARCHAR(100) NOT NULL UNIQUE,

    CONSTRAINT FK_Lamps_WorkStation
        FOREIGN KEY (StationID) REFERENCES WorkStation(StationID),

    CONSTRAINT FK_Lamps_Worker
        FOREIGN KEY (WorkerID) REFERENCES Worker(WorkerID),

    CONSTRAINT FK_Lamps_Tray
        FOREIGN KEY (TrayID) REFERENCES Tray(TrayID)
);

-- =========================================================
-- ASSEMBLY COMPONENT 
-- =========================================================
CREATE TABLE AssemblyComponent
(
    AssemblyComponentID INT IDENTITY(1,1) PRIMARY KEY,
    LampID INT NOT NULL,
    PartID INT NOT NULL,
    QuantityUsed INT NOT NULL DEFAULT 1,

    CONSTRAINT FK_AssemblyComponent_Lamps
        FOREIGN KEY (LampID) REFERENCES Lamps(LampID),

    CONSTRAINT FK_AssemblyComponent_Parts
        FOREIGN KEY (PartID) REFERENCES Parts(PartID),

    CONSTRAINT UQ_AssemblyComponent_Lamp_Part
        UNIQUE (LampID, PartID)
);

-- =========================================================
-- QUALITY INSPECTION
-- =========================================================
CREATE TABLE QualityInspection
(
    InspectionID INT IDENTITY(1,1) PRIMARY KEY,
    LampID INT NOT NULL,
    InspectionTime DATETIME NOT NULL DEFAULT GETDATE(),
    IsDefective BIT NOT NULL,
    Notes VARCHAR(255) NULL,

    CONSTRAINT FK_QualityInspection_Lamps
        FOREIGN KEY (LampID) REFERENCES Lamps(LampID)
);

-- =========================================================
-- BIN NOTIFICATION
-- =========================================================
CREATE TABLE BinNotification
(
    NotificationID INT IDENTITY(1,1) PRIMARY KEY,
    BinID INT NOT NULL,
    NotificationType VARCHAR(50) NOT NULL,
    NotificationTime DATETIME NOT NULL DEFAULT GETDATE(),
    Status VARCHAR(30) NOT NULL,

    CONSTRAINT FK_BinNotification_Bin
        FOREIGN KEY (BinID) REFERENCES Bin(BinID)
);

-- =========================================================
-- RUNNER ACTIVITY
-- =========================================================
CREATE TABLE RunnerActivity
(
    RunnerActivityID INT IDENTITY(1,1) PRIMARY KEY,
    BinID INT NOT NULL,
    ActionType VARCHAR(50) NOT NULL,
    ActivityTime DATETIME NOT NULL DEFAULT GETDATE(),
    OldCount INT NULL,
    NewCount INT NULL,

    CONSTRAINT FK_RunnerActivity_Bin
        FOREIGN KEY (BinID) REFERENCES Bin(BinID)
);

-- =========================================================
-- SEED DATA
-- =========================================================

-- =========================================================
-- ASSEMBLY AREA
-- =========================================================
INSERT INTO AssemblyArea (TotalOrderQty, InProcessCount, ProducedCount, GoodLamps)
VALUES (500, 0, 0, 0);

-- =========================================================
-- WORK STATIONS
-- =========================================================
INSERT INTO WorkStation (StationName, Status, AssemblyAreaID, Location)
VALUES
('Station 1', 'Active', 1, 'Assembly Line A'),
('Station 2', 'Active', 1, 'Assembly Line B'),
('Station 3', 'Active', 1, 'Assembly Line C');

-- =========================================================
-- SKILLS
-- =========================================================
INSERT INTO Skills (SkillLevelName, Speed, DefectRate)
VALUES
('NewEmployee', 1.50, 0.85),
('ExperiencedWorker', 1.00, 0.50),
('SuperWorker', 0.85, 0.15);

-- =========================================================
-- WORKERS
-- =========================================================
INSERT INTO Worker (WorkerName, SkillLevelID, StationID)
VALUES
('Julia', 2, 1),   -- ExperiencedWorker at Station 1
('Bibi', 1, 2),    -- NewEmployee at Station 2
('Alex', 3, 3);    -- SuperWorker at Station 3

-- =========================================================
-- PARTS
-- =========================================================
INSERT INTO Parts (PartName, DefaultCapacity)
VALUES
('Harness', 55),
('Reflector', 35),
('Housing', 24),
('Lens', 40),
('Bulb', 60),
('Bezel', 75);

-- =========================================================
-- BINS
-- One bin per part per station
-- Station 1
-- =========================================================
INSERT INTO Bin (PartID, StationID, CurrentCount, NeedsRefill, LastReplenishment)
VALUES
(1, 1, 55, 0, GETDATE()), -- Harness
(2, 1, 35, 0, GETDATE()), -- Reflector
(3, 1, 24, 0, GETDATE()), -- Housing
(4, 1, 40, 0, GETDATE()), -- Lens
(5, 1, 60, 0, GETDATE()), -- Bulb
(6, 1, 75, 0, GETDATE()); -- Bezel

-- =========================================================
-- BINS
-- Station 2
-- =========================================================
INSERT INTO Bin (PartID, StationID, CurrentCount, NeedsRefill, LastReplenishment)
VALUES
(1, 2, 55, 0, GETDATE()),
(2, 2, 35, 0, GETDATE()),
(3, 2, 24, 0, GETDATE()),
(4, 2, 40, 0, GETDATE()),
(5, 2, 60, 0, GETDATE()),
(6, 2, 75, 0, GETDATE());

-- =========================================================
-- BINS
-- Station 3
-- =========================================================
INSERT INTO Bin (PartID, StationID, CurrentCount, NeedsRefill, LastReplenishment)
VALUES
(1, 3, 55, 0, GETDATE()),
(2, 3, 35, 0, GETDATE()),
(3, 3, 24, 0, GETDATE()),
(4, 3, 40, 0, GETDATE()),
(5, 3, 60, 0, GETDATE()),
(6, 3, 75, 0, GETDATE());

-- =========================================================
-- TRAYS
-- =========================================================
INSERT INTO Tray (Capacity, TrayStatus, SentToTestingTime)
VALUES
(12, 'InUse', NULL),
(12, 'Empty', NULL),
(12, 'Empty', NULL);

-- =========================================================
-- SAMPLE LAMP
-- =========================================================
INSERT INTO Lamps (Barcode, StationID, WorkerID, TrayID, IsDefective, AssemblyTime)
VALUES
('LAMP-S1-002', 1, 1, 1, 0, 60.00),
('LAMP-S2-001', 2, 2, 1, 1, 90.00);

-- =========================================================
-- SAMPLE QUALITY INSPECTION
-- =========================================================
INSERT INTO QualityInspection (LampID, InspectionTime, IsDefective, Notes)
VALUES
(1, GETDATE(), 0, 'Passed inspection');

-- =========================================================
-- SAMPLE RUNNER ACTIVITY
-- =========================================================
INSERT INTO RunnerActivity (BinID, ActionType, ActivityTime, OldCount, NewCount)
VALUES
(1, 'Refill', GETDATE(), 4, 59);

-- =========================================================
-- SAMPLE BIN NOTIFICATION
-- =========================================================
INSERT INTO BinNotification (BinID, NotificationType, NotificationTime, Status)
VALUES
(1, 'LowStock', GETDATE(), 'Open');

-- =========================================================
-- TESTS
-- =========================================================
INSERT INTO Lamps (Barcode, StationID, WorkerID, TrayID, IsDefective, AssemblyTime)
VALUES
('LAMP-S1-001', 1, 1, 1, 0, 60.00);

INSERT INTO AssemblyComponent (LampID, PartID, QuantityUsed)
VALUES
(1,1,1),(1,2,1),(1,3,1),(1,4,1),(1,5,1),(1,6,1),
(2,1,1),(2,2,1),(2,3,1),(2,4,1),(2,5,1),(2,6,1);

INSERT INTO QualityInspection (LampID, InspectionTime, IsDefective, Notes)
VALUES
(1, GETDATE(), 0, 'Pass'),
(2, GETDATE(), 1, 'Fail');

INSERT INTO BinNotification (BinID, NotificationType, NotificationTime, Status)
VALUES
(1, 'LowStock', GETDATE(), 'Open');

INSERT INTO RunnerActivity (BinID, ActionType, ActivityTime, OldCount, NewCount)
VALUES
(1, 'Refill', GETDATE(), 4, 59);

SELECT * FROM Lamps;
SELECT * FROM AssemblyComponent;
SELECT * FROM QualityInspection;
SELECT * FROM BinNotification;
SELECT * FROM RunnerActivity;

--------------------------------------------------------------------------------------
------------------------------ == STORED PROCEDURES == -------------------------------
-- reusable database actions
--------------------------------------------------------------------------------------
-- =========================================================
-- PROCEDURE: Start Lamp Assembly
-- DESCRIPTION: Inserts a new lamp record and returns LampID
-- =========================================================
IF OBJECT_ID('dbo.sp_StartLampAssembly', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_StartLampAssembly;
GO

CREATE PROCEDURE dbo.sp_StartLampAssembly
    @Barcode VARCHAR(100),
    @StationID INT,
    @WorkerID INT,
    @TrayID INT = NULL,
    @AssemblyTime DECIMAL(8,2),
    @LampID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Lamps (Barcode, StationID, WorkerID, TrayID, IsDefective, AssemblyTime)
    VALUES (@Barcode, @StationID, @WorkerID, @TrayID, 0, @AssemblyTime);

    SET @LampID = SCOPE_IDENTITY();
END;
GO

-- =========================================================
-- PROCEDURE: Add Assembly Components
-- =========================================================
IF OBJECT_ID('dbo.sp_AddAssemblyComponents', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_AddAssemblyComponents;
GO

CREATE PROCEDURE dbo.sp_AddAssemblyComponents
    @LampID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO AssemblyComponent (LampID, PartID, QuantityUsed)
    SELECT @LampID, PartID, 1
    FROM Parts;
END;
GO


-- =========================================================
-- PROCEDURE: Consume Parts From Bins
-- =========================================================
IF OBJECT_ID('dbo.sp_ConsumePartsFromBins', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_ConsumePartsFromBins;
GO

CREATE PROCEDURE dbo.sp_ConsumePartsFromBins
    @StationID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS
    (
        SELECT 1
        FROM Bin
        WHERE StationID = @StationID
          AND CurrentCount < 1
    )
    BEGIN
        RAISERROR('Not enough parts in one or more bins.', 16, 1);
        RETURN;
    END

    UPDATE Bin
    SET CurrentCount = CurrentCount - 1
    WHERE StationID = @StationID;
END;
GO


-- =========================================================
-- PROCEDURE: Record Quality Inspection
-- =========================================================
IF OBJECT_ID('dbo.sp_RecordQualityInspection', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_RecordQualityInspection;
GO

CREATE PROCEDURE dbo.sp_RecordQualityInspection
    @LampID INT,
    @IsDefective BIT,
    @Notes VARCHAR(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO QualityInspection (LampID, InspectionTime, IsDefective, Notes)
    VALUES (@LampID, GETDATE(), @IsDefective, @Notes);

    UPDATE Lamps
    SET IsDefective = @IsDefective
    WHERE LampID = @LampID;
END;
GO


-- =========================================================
-- PROCEDURE: Refill Bin
-- =========================================================
IF OBJECT_ID('dbo.sp_RefillBin', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_RefillBin;
GO

CREATE PROCEDURE dbo.sp_RefillBin
    @BinID INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @OldCount INT;
    DECLARE @PartID INT;
    DECLARE @DefaultCapacity INT;
    DECLARE @NewCount INT;

    SELECT 
        @OldCount = CurrentCount,
        @PartID = PartID
    FROM Bin
    WHERE BinID = @BinID;

    SELECT @DefaultCapacity = DefaultCapacity
    FROM Parts
    WHERE PartID = @PartID;

    SET @NewCount = @OldCount + @DefaultCapacity;

    UPDATE Bin
    SET CurrentCount = @NewCount,
        NeedsRefill = 0,
        LastReplenishment = GETDATE()
    WHERE BinID = @BinID;

    INSERT INTO RunnerActivity (BinID, ActionType, ActivityTime, OldCount, NewCount)
    VALUES (@BinID, 'Refill', GETDATE(), @OldCount, @NewCount);
END;
GO


-- =========================================================
-- PROCEDURE: Run Full Lamp Cycle
-- DESCRIPTION: Starts lamp, adds components, consumes parts, and records inspection
-- =========================================================
IF OBJECT_ID('dbo.sp_RunLampCycle', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_RunLampCycle;
GO

CREATE PROCEDURE dbo.sp_RunLampCycle
    @Barcode VARCHAR(100),
    @StationID INT,
    @WorkerID INT,
    @TrayID INT = NULL,
    @AssemblyTime DECIMAL(8,2),
    @IsDefective BIT,
    @Notes VARCHAR(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @LampID INT;

    INSERT INTO Lamps (Barcode, StationID, WorkerID, TrayID, IsDefective, AssemblyTime)
    VALUES (@Barcode, @StationID, @WorkerID, @TrayID, 0, @AssemblyTime);

    SET @LampID = SCOPE_IDENTITY();

    INSERT INTO AssemblyComponent (LampID, PartID, QuantityUsed)
    SELECT @LampID, PartID, 1
    FROM Parts;

    IF EXISTS
    (
        SELECT 1
        FROM Bin
        WHERE StationID = @StationID
          AND CurrentCount < 1
    )
    BEGIN
        RAISERROR('Not enough parts in one or more bins.', 16, 1);
        RETURN;
    END

    UPDATE Bin
    SET CurrentCount = CurrentCount - 1
    WHERE StationID = @StationID;

    INSERT INTO QualityInspection (LampID, InspectionTime, IsDefective, Notes)
    VALUES (@LampID, GETDATE(), @IsDefective, @Notes);

    UPDATE Lamps
    SET IsDefective = @IsDefective
    WHERE LampID = @LampID;
END;
GO

-- =========================================================
-- PROCEDURE: Assign Worker To Station
-- DESCRIPTION: Updates the station assigned to a worker
-- =========================================================
IF OBJECT_ID('dbo.sp_AssignWorkerToStation', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_AssignWorkerToStation;
GO

CREATE PROCEDURE dbo.sp_AssignWorkerToStation
    @WorkerID INT,
    @StationID INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE Worker
    SET StationID = @StationID
    WHERE WorkerID = @WorkerID;
END;
GO


-- =========================================================
-- PROCEDURE: Get Low Stock Bins
-- DESCRIPTION: Returns bins that need refill
-- =========================================================
IF OBJECT_ID('dbo.sp_GetLowStockBins', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_GetLowStockBins;
GO

CREATE PROCEDURE dbo.sp_GetLowStockBins
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        b.BinID,
        b.StationID,
        ws.StationName,
        b.PartID,
        p.PartName,
        b.CurrentCount,
        b.NeedsRefill,
        b.LastReplenishment
    FROM Bin b
    INNER JOIN WorkStation ws ON b.StationID = ws.StationID
    INNER JOIN Parts p ON b.PartID = p.PartID
    WHERE b.NeedsRefill = 1
    ORDER BY b.StationID, b.PartID;
END;
GO


-- =========================================================
-- PROCEDURE: Close Bin Notification
-- DESCRIPTION: Closes open notifications for a bin
-- =========================================================
IF OBJECT_ID('dbo.sp_CloseBinNotification', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_CloseBinNotification;
GO

CREATE PROCEDURE dbo.sp_CloseBinNotification
    @BinID INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE BinNotification
    SET Status = 'Closed'
    WHERE BinID = @BinID
      AND Status = 'Open';
END;
GO


-- =========================================================
-- PROCEDURE: Send Tray To Testing
-- DESCRIPTION: Marks a tray as sent to testing
-- =========================================================
IF OBJECT_ID('dbo.sp_SendTrayToTesting', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_SendTrayToTesting;
GO

CREATE PROCEDURE dbo.sp_SendTrayToTesting
    @TrayID INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE Tray
    SET TrayStatus = 'SentToTesting',
        SentToTestingTime = GETDATE()
    WHERE TrayID = @TrayID;
END;
GO


-- =========================================================
-- PROCEDURE: Create New Tray
-- DESCRIPTION: Inserts a new tray record
-- =========================================================
IF OBJECT_ID('dbo.sp_CreateNewTray', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_CreateNewTray;
GO

CREATE PROCEDURE dbo.sp_CreateNewTray
    @Capacity INT,
    @TrayStatus VARCHAR(30) = 'Empty'
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Tray (Capacity, TrayStatus, SentToTestingTime)
    VALUES (@Capacity, @TrayStatus, NULL);
END;
GO

--------------------------------------------------------------------------------------
----------------------------------- == TRIGGERS == -----------------------------------
-- make the database react automatically when something changes
--------------------------------------------------------------------------------------

-- =========================================================
-- TRIGGER: Low Stock Notification
-- DESCRIPTION: Flags low stock bins and creates a notification
-- =========================================================
IF OBJECT_ID('dbo.trg_LowStockNotification', 'TR') IS NOT NULL
    DROP TRIGGER dbo.trg_LowStockNotification;
GO

CREATE TRIGGER dbo.trg_LowStockNotification
ON Bin
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @LowStockThreshold INT;

    SELECT @LowStockThreshold = CAST(ConfigValue AS INT)
    FROM Configuration
    WHERE ConfigName = 'LowStockThreshold';

    UPDATE b
    SET NeedsRefill = CASE
                        WHEN i.CurrentCount <= @LowStockThreshold THEN 1
                        ELSE 0
                      END
    FROM Bin b
    INNER JOIN inserted i ON b.BinID = i.BinID;

    INSERT INTO BinNotification (BinID, NotificationType, NotificationTime, Status)
    SELECT i.BinID, 'LowStock', GETDATE(), 'Open'
    FROM inserted i
    INNER JOIN deleted d ON i.BinID = d.BinID
    WHERE i.CurrentCount <= @LowStockThreshold
      AND d.CurrentCount > @LowStockThreshold;
END;
GO


-- =========================================================
-- TRIGGER: Clear Refill Flag After Refill
-- DESCRIPTION: Clears NeedsRefill when bin count goes above threshold
-- =========================================================
IF OBJECT_ID('dbo.trg_ClearRefillFlagAfterRefill', 'TR') IS NOT NULL
    DROP TRIGGER dbo.trg_ClearRefillFlagAfterRefill;
GO

CREATE TRIGGER dbo.trg_ClearRefillFlagAfterRefill
ON Bin
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @LowStockThreshold INT;

    SELECT @LowStockThreshold = CAST(ConfigValue AS INT)
    FROM Configuration
    WHERE ConfigName = 'LowStockThreshold';

    UPDATE b
    SET NeedsRefill = 0
    FROM Bin b
    INNER JOIN inserted i ON b.BinID = i.BinID
    INNER JOIN deleted d ON i.BinID = d.BinID
    WHERE i.CurrentCount > @LowStockThreshold
      AND i.CurrentCount > d.CurrentCount;
END;
GO


-- =========================================================
-- TRIGGER: Close Notification After Refill
-- DESCRIPTION: Closes open notifications when bin is refilled
-- =========================================================
IF OBJECT_ID('dbo.trg_CloseNotificationAfterRefill', 'TR') IS NOT NULL
    DROP TRIGGER dbo.trg_CloseNotificationAfterRefill;
GO

CREATE TRIGGER dbo.trg_CloseNotificationAfterRefill
ON Bin
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @LowStockThreshold INT;

    SELECT @LowStockThreshold = CAST(ConfigValue AS INT)
    FROM Configuration
    WHERE ConfigName = 'LowStockThreshold';

    UPDATE bn
    SET Status = 'Closed'
    FROM BinNotification bn
    INNER JOIN inserted i ON bn.BinID = i.BinID
    INNER JOIN deleted d ON i.BinID = d.BinID
    WHERE bn.Status = 'Open'
      AND i.CurrentCount > @LowStockThreshold
      AND i.CurrentCount > d.CurrentCount;
END;
GO